kind = "design"
previewPath = "/"
title = "Trading App Screens"
version = "1.0.0"
id = "XegfDyZt7HqfW2Bb8Ghoy"

[[services]]
localPort = 3000
name = "Component Preview Server"
paths = ["/"]

[services.env]
PORT = "3000"
BASE_PATH = "/"

[services.development]
run = "pnpm --filter @workspace/mockup-sandbox run dev"
