// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trading-app/AdminDashboard.tsx": () => import("../components/mockups/trading-app/AdminDashboard.tsx"),
  "./components/mockups/trading-app/BatchCourseManagement.tsx": () => import("../components/mockups/trading-app/BatchCourseManagement.tsx"),
  "./components/mockups/trading-app/StudentManagement.tsx": () => import("../components/mockups/trading-app/StudentManagement.tsx")
};
